[IV-23-24] Objetivo 4
pluque01/CofreSagradoVirtual pull request #22
Opened 2023-11-10 07:36 UTC by pluque01

* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ] ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
delante?
* [ ] ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [ ] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [ ] ¿Se han testeado también las excepciones?

2023-11-23 16:50 UTC, pluque01 commented
@JJ esto está listo para revisión. ¿Aviso al pobre Morad que carga ya con multitud de revisiones o me lo revisa otra persona?

2023-11-24 08:22 UTC, JJ requested changes
Me resulta un poco complicado mapear una función específica a lo que quiere el cliente en la HU #2 (o la que sea), aunque has hecho un buen trabajo con las funciones de más bajo nivel. En todo caso, eso no lo bloquea: el problema principal es el iv.yaml, que tienes un error que te saldría en el siguiente objetivo.

2023-11-24 08:22 UTC, JJ commented on doc/tools.md
> +- Ofrece soporte para declarar conjuntos de tests y funciones de limpieza.
No os enrolléis más de lo estrictamente necesario, por favor...

2023-11-24 08:22 UTC, JJ commented on internal/archivo_clientes.go
> +	"telephone": {*regexp.MustCompile(`(?i)(.*phone.*|.*tel(e|é)fono.*|.*m(o|ó)vil.*|.*n(u|ú)mero.*|.*number.*)`), *regexp.MustCompile(`\d{3}(?:[-\s]?\d{2,3}){2}`)},
Quizás deberías usar como clave "columna" también, como "telephoneColumn" o algo así; o en el par usar un struct en vez de dos elementos.

2023-11-24 08:22 UTC, JJ commented on iv.yaml
> +test: internal/tipo_datos_cliente.go
Este no es un fichero de test, y además lo has borrado...

2023-11-24 09:35 UTC, pluque01 commented
Corregido lo del `iv.yaml`
Listo para revisión @JJ

2023-11-24 10:31 UTC, JJ approved these changes
👍

2023-11-24 10:31 UTC, JJ commented on cmd/validcsv/validcsv.go
> +package main
¿Esto te lo pide el milestone? Recuerda que tienes que tener un PMV.

2023-11-26 17:51 UTC, merged