[IV-23-24]Objetivo 7
pluque01/CofreSagradoVirtual pull request #42
Opened 2023-12-05 16:49 UTC by pluque01

## Issues

* Closes #36 
* Closes #37
* Closes #38 
* Closes #39 
* Closes #40 
* Closes #41

## Lista de comprobación

* [x] ¿Se han registrado todos los eventos relevantes en la aplicación, es decir, se
  han añadido comandos para registrarlos en todos ellos?
* [x] ¿Se han seguido buenas prácticas en el uso de configuración remota?
* [x] ¿Se han explicado correctamente las decisiones técnicas que se han tomado
  sobre las bibliotecas usadas?
* [x] ¿Te has asegurado de que el fichero `.env` no se pueda añadir
accidentalente al repositorio?
* [x] ¿Los logs y la configuración están en un objeto que se *inyecta* en las
clases manejadoras para su uso?
* [x] ¿*Realmente* se usan los logs en las diferentes clases en eventos
importantes?
* [x] ¿Se testea el código creado para logs y configuración, igual que
    cualquier otro código?
* [x] ¿La clase o módulo de configuración lee *siempre* las variables de entorno?
Cuando una variable de entorno está definida con un prefijo relevante a la aplicación se lee.

2023-12-05 16:56 UTC, pluque01 commented
@JJ Listo para revisión

2023-12-11 08:09 UTC, JJ requested changes
Por favor, dale una pequeña vuelta a los criterios para elegir una biblioteca u otra y listo.

2023-12-11 08:09 UTC, JJ commented on doc/tools.md
> +- **Escalabilidad:** En relación con el punto anterior, la herramienta debe ser
Escalabilidad se refiere habitualmente a poder trabajar con diferentes instancias, más que a adaptabilidad con el proyecto (que además ya has puesto arriba)

2023-12-11 08:09 UTC, JJ commented on doc/tools.md
> +- **Facilidad de uso:** La herramienta debe ser fácil de usar, especialmente
No es muy objetivo. Aquí se aplica lo mismo que en el resto de los objetivos.

2023-12-11 08:09 UTC, JJ commented on doc/tools.md
> +y **Zerolog** voy a usar **Zerolog**, ya que ofrece mayor rendimiento, parece
Si "facilidad de uso" no es muy objetivo, el *parecer* que es más fácil, ¿te parece más o menos objetivo?

2023-12-11 08:09 UTC, JJ commented on doc/tools.md
> +[Snyk Advisor](https://snyk.io/advisor/golang/github.com/rs/zerolog).
Pero no es un criterio que hayas puesto arriba, ¿no?

2023-12-11 08:09 UTC, JJ commented on doc/tools.md
> +Viendo las opciones que tengo disponibles creo que me voy a decantar por
¿Tiene soporte para configuraciones clave-valor distribuidas? Es el criterio que has puesto...

2023-12-11 13:30 UTC, pluque01 commented
@JJ listo para revisión de nuevo

2023-12-11 16:24 UTC, JJ approved these changes
:+1: por favor, acostumbraros a cerrar siempre los comentarios con el commit en el que se haya resuelto.

2023-12-11 16:24 UTC, JJ commented on doc/tools.md
> +[Snyk Advisor](https://snyk.io/advisor/golang/github.com/rs/zerolog).
Indica siempre, por favor, el commit en el que lo has resuelto.

2023-12-11 16:45 UTC, pluque01 commented on doc/tools.md
> +[Snyk Advisor](https://snyk.io/advisor/golang/github.com/rs/zerolog).
Resuelto en 7e25de8

2023-12-11 16:45 UTC, merged