[IV-23-24] Objetivo 1
pluque01/CofreSagradoVirtual pull request #5
Opened 2023-09-22 10:46 UTC by pluque01

## Sobre los milestones

* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [x] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [x] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [x] ¿El milestone 0 es mínimo *y* viable?
* [x] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

## Sobre las historias de usuario

* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
He considerado que lo descrito en las historias de usuario era suficientemente claro
* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2023-09-25 12:25 UTC, JJ commented
Si comentáis algo en la lista de comprobación, realmente ayuda a ver si la habéis seguido de verdad (y a vosotros enviarlo con un mínimo número de problemas)

2023-09-25 12:30 UTC, JJ requested changes
Hay algunas cosas que se han aclarado con la historia de usuario (por ejemplo, si se trata de una administración o un particular), pero en #1 te comenté que debías formular claramente el problema; ahora es el momento de hacerlo, y me temo que no has ido en la dirección correcta. Conocer estadísticas no soluciona el problema, da elementos para tomar una decisión, pero las estadísticas si son demasiado simples no serían una lógica de negocio adecuada, y si lo que tratas es de predecir, hay todo tipo de problemas asociados a eso.

2023-09-25 12:30 UTC, JJ commented on doc/milestones.md
> +* Comprension del problema y búsqueda de las mejores fuentes de datos para resolverlo.
¿Te parece que "comprensión" describa un producto?

2023-09-25 12:30 UTC, JJ commented on doc/milestones.md
> +* Creación del modelo de predicción estadístico.
¿Un "modelo" describe un producto?

2023-09-25 12:30 UTC, JJ commented on doc/milestones.md
> +El producto será valido si dado un indicador y un número de períodos la estimación acierta en la tendencia (positiva/negativa) dentro de un margen de error estándar.
typo en `valido`

2023-09-29 09:01 UTC, pluque01 commented
## Sobre los milestones

* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
Sí, en mi opinión constituyen una guía suficiente.
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
Sí.
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
Sí
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
Sí.
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
El milestone 0 corresponde con la creación del código modularizado del problema.
* [x] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
Todos describen un PMV.
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
Son graduales.
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
Sí, el milestone 0 es interno.
* [x] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
Sí, ya lo he comentado.
* [x] ¿El milestone 0 es mínimo *y* viable?
Sí lo es.
* [x] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
Se indican los requisitos técnicos para cada milestone
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?
No.

## Sobre las historias de usuario

* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
El concepto de proyecto que se desplegará en la nube es un poco ambiguo, pero yo considero que sí.
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
Están descritos con claridad, por lo que no he creado documentos aparte.
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
Las historias tiene coherencia suficiente por lo que no hay un "user journey"
* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?
El producto es de necesidad para el usuario y al contrario.

2023-09-29 09:02 UTC, pluque01 commented
Listo para revisión @JJ

2023-09-29 09:28 UTC, JJ commented
Por favor, la lista de comprobación en el cuerpo, es decir, el primer comentario.

2023-09-29 09:50 UTC, pluque01 commented
> Por favor, la lista de comprobación en el cuerpo, es decir, el primer comentario.

Arreglado

2023-09-29 15:52 UTC, JJ commented
Ya que lo has hecho de nuevo, sería conveniente que lo revisara alguien; sugiero a @migueruiz y @carlosservi

2023-10-01 08:02 UTC, migueruiz commented
Hola seré tu revisor, un gusto.

2023-10-01 08:05 UTC, migueruiz commented on doc/milestones.md
> +## Milestone 0
Creo que deberías de detallar el objetivo y el nombre de los Milestones, para poder diferenciar ambas partes adecuadamente.

2023-10-01 08:05 UTC, migueruiz commented on doc/user-stories.md
> +Tengo una pequeña tienda de ropa en la que vendo mis diseños. Tengo una hoja de cálculo en la que apunto las ventas de cada día, pero en ocasiones por las prisas o por un error mío, no apunto algún d
Tu historia de usuario considero que esté correcta, pero quizás podrías darle un poco más de contexto, como en que momento quieres que te avise del error, o si puede brindarte alguna solución.

2023-10-01 10:46 UTC, carlosservi commented
Hola @pluque01, me ha tocado revisar tu proyecto. Pienso un poco igual que @migueruiz. No queda claro si la herramienta te indica los errores mientras estás rellenando el CSV o si, por el contrario, le das el archivo una vez relleno y te detecta los errores, arreglando los que puede. Tal vez sean las dos cosas, pero pienso que deberías dejarlo un poco más claro. Espero haberte sido de ayuda.

2023-10-01 16:33 UTC, pluque01 commented
Muchas gracias a @migueruiz y @carlosservi, he implementado las sugerencias que me habéis dado. Agradecería si pudieseis darme el visto bueno para mandarlo a revisión.

2023-10-02 08:54 UTC, migueruiz approved these changes
Creo que ya esta correcto, para que lo vea el profesor @JJ

2023-10-02 09:10 UTC, JJ requested changes
Muchas gracias a @carlosservi y @migueruiz por el trabajo; creo que han mejorado bastante, y los problemas que hay ahora son bastante sutiles.
Aparte de lo comentado sobre el orden (o simplemente supresión de la que es ahora la 01), creo que deberías ser más preciso sobre los tipos de datos que va a haber almacenados en cada columna para que se pueda hacer un modelo adecuado en el objetivo 2.

2023-10-02 09:10 UTC, JJ commented on README.md
> +Las historias de usuario se pueden consultar [aquí](/doc/user-stories.md).
Estos URLs están mal; usa URL relativos y no absolutos.

2023-10-02 09:10 UTC, JJ commented on doc/milestones.md
> +## \[M0\] Modelo del problema
¿Por qué el escape?

2023-10-02 09:10 UTC, JJ commented on doc/user-stories.md
> +Tengo una pequeña tienda de ropa en la que vendo mis diseños. Tengo una hoja de cálculo en la que apunto las ventas de cada día, pero en ocasiones por las prisas o por un error mío, no apunto algún d
Por lo que entendí en el objetivo 0, no sólo se trataba de que faltara (que tendría una lógica de negocio excesivamente simple) sino que tratara de detectar errores en la transcripción e incluso tratar de corregirlos, ¿no?

2023-10-02 09:10 UTC, JJ commented on doc/user-stories.md
> +En mis trabajos de investigación es imprescindible que los datos que obtengo de las muestras que analizo estén bien organizados y sean correctos. Para ello, utilizo ficheros CSV para guardarlos. Sin
En la asignatura os dije que le HU01 debería contener una lógica de negocio que se pudiera programar en el objetivo 4. Si la lógica de negocio en la historia de usuario 01 es demasiado simple, no va a dar lugar a un modelo complejo en el siguiente objetivo.

2023-10-02 17:09 UTC, pluque01 commented
Gracias por las recomendaciones, he intentado adaptarme a ellas. Espero estar más cerca de alcanzar el objetivo.

Listo para revisión @JJ

2023-10-02 17:21 UTC, JJ approved these changes
:+1: 
Con gracias una vez más a @migueruiz y @carlosservi por la ayuda prestada.

2023-10-02 17:21 UTC, JJ commented on doc/milestones.md
> +PMV: Código modularizado del problema.
¿De qué del problema? Por el contexto se sabe, pero siempre es conveniente pecar de repetido más que de impreciso.

2023-10-02 17:23 UTC, merged