[IV-23-24] Objetivo 2
pluque01/CofreSagradoVirtual pull request #8
Opened 2023-10-05 07:28 UTC by migueruiz

Debatido en #7 closes #7

2023-10-23 13:37 UTC, migueruiz commented
Hola @pluque01 ya he añadido el código. Si crees que hay algún problema coméntamelo, lo arreglare encantado. Gracias de antemano 😁.

2023-10-23 14:55 UTC, migueruiz commented
Hola @pluque01 ya he añadido el código. Si crees que hay algún problema coméntamelo, lo arreglare encantado. Gracias de antemano 😁.

2023-10-23 16:08 UTC, pluque01 commented
Hola @migueruiz!
Yo lo veo bastante bien. De todas formas es el profesor el que debe dar el visto bueno 😅.
Como sugerencia de mejora, en Go los getters se nombran con la primera letra del nombre de la variable en mayúscula: `GetApellidos() -> Apellidos()`

2023-10-23 16:14 UTC, migueruiz commented
@pluque01 Creo que en este objetivo, tu primero debes de validar si crees que lo que te he proporcionado es correcto, para que posteriormente el profesor lo valide. Además debes de poner tu en un comentario lo que corresponde al usuario  propietario del proyecto.
De acuerdo! tomare en cuenta tu consejo. Gracias! 😄

2023-10-23 16:48 UTC, pluque01 commented
Ahí voy.

* [x] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [x] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [x] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [x] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

Todo correcto, muy buen trabajo 👍

2023-10-23 16:48 UTC, pluque01 approved these changes

2023-10-23 17:07 UTC, migueruiz commented
Perdóname, también debes de mencionar tú al profesor para la evaluación del objetivo, que me he confundido y pensaba que era yo quien debía hacerlo. 😅

2023-10-23 17:15 UTC, pluque01 commented
No te preocupes @migueruiz.
@JJ listo para revisión :))

2023-10-23 17:25 UTC, JJ requested changes
En general, deberías intentar profundizar un poco más en la modelización del problema. Esencialmente has creado estructuras con los mismos nombres que la HU, sin más modelización que separarlos en estructuras diferentes y usar un `string` para todas. Un modelo requiere algo más, especialmente teniendo en cuenta la lógica de negocio. @pluque01, sobre todo deberíais mirar cómo tomaríais este código para empezar a trabajar en el 4, y si parece que hay mucho más que hacer. En este caso, me temo que es posible que sí, ¿no?
Si fuera posible, alguno de los que ya haya terminado el objetivo 1, @luciaansino o @enaraque, sería genial que pudieran echarle un vistazo también cuando hagáis la segunda vuelta.

2023-10-23 17:25 UTC, JJ commented on internal/apellidos.go
> +// Defininción de la estructura Apellidos
No debes usar nunca comentarios, salvo docstrings (es decir, los que sirvan para generar automáticamente para la documentación)

2023-10-23 17:25 UTC, JJ commented on internal/apellidos.go
> +	apellidos string
¿Dos apellidos, un string?

2023-10-23 17:25 UTC, JJ commented on internal/apellidos.go
> +func (a *Apellidos) SetApellidos(apellidos string) {
Por favor, mira [los errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-2.md#sobre-el-c%C3%B3digo-definido). Los setters rara vez se pueden justificar, pero en este caso que es un solo atributo, menos todavía.

2023-10-23 17:25 UTC, JJ commented on internal/nombre.go
> +type Nombre struct {
¿Hay alguna razón por la que nombre y apellidos sean "tipos" diferentes y estén separados?

2023-10-23 17:25 UTC, JJ commented on internal/telefono.go
> +package apellidos
A ver, sé que estaba yo presente cuando CoPilot te sugirió esto, y esto compila sin mucho problema; pero ¿estás seguro que este es el nombre que deben llevar? La función main a ejecutar suele ir en el package `main`. ¿En qué package irá lo que está en `internal`?

2023-10-23 17:33 UTC, migueruiz commented on internal/apellidos.go
> +func (a *Apellidos) SetApellidos(apellidos string) {
De acuerdo, entendí mal el concepto, gracias por el apunte. 😄

2023-10-23 17:45 UTC, migueruiz commented on internal/telefono.go
> +package apellidos
De hecho, quería preguntarle sobre eso, porque he estado buscando y no he encontrado bien, que debería de poner en el caso en que este en internal, ya que en el resto de casos me recomienda que ponga main. Pero no se exactamente, si pudiese ayudarme. 😅

2023-10-23 17:47 UTC, JJ commented on internal/telefono.go
> +package apellidos
Otro compañero he visto que lo ha hecho así, pero no recuerdo quién. ¿Igual mejor lo preguntas en el grupo de Telegram, para que te lo diga quien lo haya hecho?
En todo caso, puede ser `main` o `internal`, pero casi seguro que no llevan el nombre del fichero.

2023-10-23 17:48 UTC, migueruiz commented
@pluque01 Necesitaría que eliminases el issue #11, ya que con la nueva modificación, la identificación del usuario de nombre y apellidos pertenecen al mismo issue.

2023-10-23 17:52 UTC, JJ commented
> @pluque01 Necesitaría que eliminases el issue #11, ya que con la nueva modificación, la identificación del usuario de nombre y apellidos pertenecen al mismo issue.

No tienes que eliminar ningún issue. Los issues son para escribir código, no para ficheros diferentes ni obligan a que estén así. Puede haber un issue por atributo, ¿por qué no?

2023-10-23 17:55 UTC, migueruiz commented
> > @pluque01 Necesitaría que eliminases el issue #11, ya que con la nueva modificación, la identificación del usuario de nombre y apellidos pertenecen al mismo issue.
> 
> No tienes que eliminar ningún issue. Los issues son para escribir código, no para ficheros diferentes ni obligan a que estén así. Puede haber un issue por atributo, ¿por qué no?

De acuerdo!, entendí que cada issue se refería expresamente a un fichero en particular, perdone por la confusión. 😅

2023-10-23 17:58 UTC, migueruiz commented
@pluque01 He cambiado el contenido de los archivos, compruébalo por si la nueva estructura que he definido yo, te parece correcta, o si quieres que haga algún cambio. 😄

2023-10-24 07:10 UTC, pluque01 commented
> @pluque01 He cambiado el contenido de los archivos, compruébalo por si la nueva estructura que he definido yo, te parece correcta, o si quieres que haga algún cambio. 😄 ¿También había pensado en crear una nueva estructura cliente, que tenga de información, las otras estructuras que he creado anteriormente, que te parece?

Como sugerencia en vez de hacer dos variables que sean `apellido1` y `apellido2` puedes hacer un array de apellidos. Lo de agrupar todos los campos en una estructura lo veo bien para la modelización del problema. Por cierto, las versiones de Go en los ficheros `iv.yaml` y `go.mod` son diferentes.

Un saludo 👋

2023-10-24 07:16 UTC, JJ commented
> > @pluque01 He cambiado el contenido de los archivos, compruébalo por si la nueva estructura que he definido yo, te parece correcta, o si quieres que haga algún cambio. 😄 ¿También había pensado en crear una nueva estructura cliente, que tenga de información, las otras estructuras que he creado anteriormente, que te parece?
> 
> @migueruiz Como sugerencia en vez de hacer dos variables que sean `apellido1` y `apellido2` puedes hacer un array de apellidos. Lo de agrupar todos los campos en una estructura lo veo bien para la modelización del problema. Por cierto, las versiones de Go en los ficheros `iv.yaml` y `go.mod` son diferentes.

iv.yaml no necesita ninguna versión.

2023-10-24 07:26 UTC, pluque01 commented on iv.yaml
> +version: 1.15.2
Elimina el campo versión entonces.

2023-10-24 08:29 UTC, migueruiz commented
@pluque01 Ya he cambiado todo y añadido todo lo necesario que habíamos comentado, si crees que necesita otro repaso el proyecto no dudes en avisarme. Muchas gracias por tu compresión! 😄 y gracias también a @JJ por sus apuntes, para evitar que haya más complicaciones creadas por mi que de las necesarias en el proyecto! 😄

2023-10-24 08:40 UTC, pluque01 reviewed
Te he hecho un comentario, lo demás lo veo bien para que pase a revisión. Muchas gracias por el trabajo realizado 😁

2023-10-24 08:40 UTC, pluque01 commented on internal/nombre.go
> +func (n *Nombre) Apellido2() string {
Creo que no es necesario dos get diferentes para los apellidos, puedes devolver el array directamente.

2023-10-24 08:50 UTC, migueruiz commented
@pluque01 Realizado el cambio! 
Si crees que esta listo agradecería que avisases al profesor para que hiciese otra revisión. Muchas gracias por tus ayudas y consejos! 😄

2023-10-24 14:07 UTC, pluque01 commented
@JJ
Listo para revisión el trabajo de @migueruiz :))

2023-10-24 14:21 UTC, pluque01 approved these changes

2023-10-24 15:15 UTC, JJ commented
Os recuerdo que el formato correcto de los commits son 

- 50 caracteres que incluyan el número de issue
- espacio en blanco
- 80 caracteres

No describáis lo qeu es obvio, el fichero qeu se está modificando, por ejemplo. Decid por qué lo estáis haciendo. Por ejemplo, comprobad si este https://github.com/pluque01/CofreSagradoVirtual/pull/8/commits/0873d8ac8040f391608deb61a324c59c311e5b91 (y los siguientes) lo siguen.

2023-10-24 15:23 UTC, JJ requested changes
Gracias por hacer las modificaciones tan rápido, y creo que algo habéis aprendido pro el camino, sobre todo el layout interno de Go. Desgraciadamente, creo que no estáis siguiendo la metodología correcta para hacer el modelo. DDD ayuda en eso, pero también crear una serie de issues que te vayan guiando hacia qué estructuras de datos hacer y no. También rogaría a @pluque01 que *realmente* mirara si con una estructura de datos que representa un cliente y otra que representa un nombre y un teléfono puede empezar a programar una lógica de negocio que se basa, sobre todo, en extraer información de tablas de datos. Tablas de datos que, por cierto, no veo que aparezcan en el modelo

2023-10-24 15:23 UTC, JJ commented on internal/cliente.go
> +func (c *Cliente) Telefono() string {
¿Qué hemos dicho de [los getters](https://github.com/JJ/IV-/blob/master/errores/errores-objetivo-2.md#sobre-el-c%C3%B3digo-definido)?

2023-10-24 15:23 UTC, JJ commented on internal/cliente.go
> +type Cliente struct {
Esta estructura de datos se crea en este commit https://github.com/pluque01/CofreSagradoVirtual/commit/29891dd0dfad2728fd404648321a9b3171d22f9f, que no hace referencia a ningún issue. Como tal, no es correcta ni incorrecta: simplemente hay que borrarla, porque no se puede probar que aporte valor al cliente.
*Todo* el código que se cree tiene que poder trazarse hasta la historia de usuario que usa, para poder afirmar que efectivamente está bien (o no)

2023-10-24 15:23 UTC, JJ commented on internal/nombre.go
> +type Nombre struct {
No se puede resolver directamente, se pone en el comentario en qué commit se ha resuelto antes.

2023-10-24 15:23 UTC, JJ commented on internal/telefono.go
> +type Telefono struct {
El commit que crea esto se llama "cambio nombre carpeta" https://github.com/pluque01/CofreSagradoVirtual/commit/bc099fafaf630e4e26a698fc495e017c70598a5c Tampoco se puede saber qué HU sirve.

2023-10-24 15:23 UTC, JJ commented on internal/telefono.go
> +	telefono string
Por otro lado, en cualquier metodología se trata de buscar el tipo de datos más adecuado para representar un dato, ese es un modelo del problema. Si aquí ponemos AZ++33 ¿se quejará Go de que lo haga?

2023-10-24 15:28 UTC, migueruiz commented on internal/telefono.go
> +	telefono string
Hola profesor, lo estuve comentando con el compañero, y me dijo que era mejor guardar un string porque en el caso en que se guardasen números extranjeros (refiriendose a +34, etc.), no se si a pesar de ello es mejor cambiarlo, y ponerlo solo como un int en vez de string.

2023-10-24 15:32 UTC, JJ commented on internal/telefono.go
> +	telefono string
Hola estudiante.
El código debe ser resultado de la metodología y de tu mejor criterio, no de un comentario con un compañero. Si el compañero sabe que hace falta un string, pone un string, no te pide a ti que lo pongas.
Si hace falta guardar *números* extranjeros, se aporta esa información al issue y se tiene en cuenta a la hora de incluir el número de cifras o lo que sea. Pero los tipos tienen que ajustarse *siempre* a lo almacenado porque si no cada vez que uses el número o lo modifiques vas a tener que comprobar el formato.

2023-10-24 15:34 UTC, migueruiz commented on internal/telefono.go
> +	telefono string
De acuerdo @JJ , en el momento que acabe la clase que estoy por empezar, intentare arreglar todo. Gracias por sus apuntes. 😄

2023-10-24 15:36 UTC, migueruiz commented
> Gracias por hacer las modificaciones tan rápido, y creo que algo habéis aprendido pro el camino, sobre todo el layout interno de Go. Desgraciadamente, creo que no estáis siguiendo la metodología correcta para hacer el modelo. DDD ayuda en eso, pero también crear una serie de issues que te vayan guiando hacia qué estructuras de datos hacer y no. También rogaría a @pluque01 que _realmente_ mirara si con una estructura de datos que representa un cliente y otra que representa un nombre y un teléfono puede empezar a programar una lógica de negocio que se basa, sobre todo, en extraer información de tablas de datos. Tablas de datos que, por cierto, no veo que aparezcan en el modelo

@JJ ¿Que debería de hacer entonces? ¿Esperar a que mi compañero piense en lo que le ha comentado? ¿O sigo programando en función a lo que se requiere?

2023-10-24 15:42 UTC, JJ commented
> > Gracias por hacer las modificaciones tan rápido, y creo que algo habéis aprendido pro el camino, sobre todo el layout interno de Go. Desgraciadamente, creo que no estáis siguiendo la metodología correcta para hacer el modelo. DDD ayuda en eso, pero también crear una serie de issues que te vayan guiando hacia qué estructuras de datos hacer y no. También rogaría a @pluque01 que _realmente_ mirara si con una estructura de datos que representa un cliente y otra que representa un nombre y un teléfono puede empezar a programar una lógica de negocio que se basa, sobre todo, en extraer información de tablas de datos. Tablas de datos que, por cierto, no veo que aparezcan en el modelo
> 
> @JJ ¿Que debería de hacer entonces? ¿Esperar a que mi compañero piense en lo que le ha comentado? ¿O sigo programando en función a lo que se requiere?

Mi consejo es que esperes hasta el jueves, y vemos tranquilamente cómo irlo haciendo, desarrollando issues a partir de la HU y demás. Si quieres irlo haciendo de aquí a entonces adelante, pero mi opinión (es mi opinión solo) que te sería más fácil empezar desde cero creando o reescribiendo los issues existentes y trabajando a partir de lo que salga.

En algunos casos creo que os estáis fijando en el resultado final de la lógica de negocio más que en el proceso, que es lo más importante. Le ha pasado a @marioguisado y a ti también. Quizás porque sea más sencillo, pero siempre lo más importante es modelizar para aplicar la lógica de negocio, que aquí realmente no estás teniendo en cuenta.

2023-10-24 15:45 UTC, migueruiz commented
> > > Gracias por hacer las modificaciones tan rápido, y creo que algo habéis aprendido pro el camino, sobre todo el layout interno de Go. Desgraciadamente, creo que no estáis siguiendo la metodología correcta para hacer el modelo. DDD ayuda en eso, pero también crear una serie de issues que te vayan guiando hacia qué estructuras de datos hacer y no. También rogaría a @pluque01 que _realmente_ mirara si con una estructura de datos que representa un cliente y otra que representa un nombre y un teléfono puede empezar a programar una lógica de negocio que se basa, sobre todo, en extraer información de tablas de datos. Tablas de datos que, por cierto, no veo que aparezcan en el modelo
> > 
> > 
> > @JJ ¿Que debería de hacer entonces? ¿Esperar a que mi compañero piense en lo que le ha comentado? ¿O sigo programando en función a lo que se requiere?
> 
> Mi consejo es que esperes hasta el jueves, y vemos tranquilamente cómo irlo haciendo, desarrollando issues a partir de la HU y demás. Si quieres irlo haciendo de aquí a entonces adelante, pero mi opinión (es mi opinión solo) que te sería más fácil empezar desde cero creando o reescribiendo los issues existentes y trabajando a partir de lo que salga.
> 
> En algunos casos creo que os estáis fijando en el resultado final de la lógica de negocio más que en el proceso, que es lo más importante. Le ha pasado a @MarioGuisado y a ti también. Quizás porque sea más sencillo, pero siempre lo más importante es modelizar para aplicar la lógica de negocio, que aquí realmente no estás teniendo en cuenta.

De acuerdo, entonces esperaré al jueves para desarrollarlo como usted me indica. 😄 Y pedir disculpas a @pluque01 por no haber hecho un buen trabajo por ahora... 😞

2023-10-24 15:47 UTC, pluque01 commented
No tienes que pedirme disculpas, te pido disculpas yo por no haber sido de más ayuda :((

2023-10-24 15:56 UTC, migueruiz commented
> No tienes que pedirme disculpas, te pido disculpas yo por no haber sido de más ayuda :((

Amigos los dos 🤝, solucionaremos los dos lo necesario! 😄

2023-10-27 08:04 UTC, migueruiz commented
@pluque01 He hecho modificaciones, cuando puedas revisalo, disculpa por las molestias. 😞

2023-10-27 08:24 UTC, pluque01 commented
Veo que has hecho un giro de 180º en la implementación. Entiendo que este modelo me permitirá asignar una expresión regular a cada tipo de dato para su validación. Enhorabuena por el trabajo realizado, te lo has currado. 

* [x] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [x] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [x] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [x] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

Listo para revision @JJ

2023-10-27 08:25 UTC, pluque01 approved these changes

2023-10-27 08:41 UTC, migueruiz commented
@pluque01 Ya he arreglado los comentarios que hemos estado diciendo en clase. Gracias por tu compresión. 😄

2023-10-27 10:02 UTC, JJ approved these changes
👍 voy a suponer que el `package main` está bien y no hay que poner `package internal` como decían en la respuesta a la pregunta en Telegram. Salvo eso, ya lo hemos hablado, correcto aunque minimalista.

2023-10-30 14:56 UTC, merged